[package]
name = "app"
version.workspace = true
edition.workspace = true

[dependencies]
datamodel = { path = "../datamodel" }
command = { path = "../command" }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"