[package]
name = "command"
version.workspace = true
edition.workspace = true

[dependencies]

datamodel = { path = "../datamodel" }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"