[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.26.2"
log = "0.4.27"
futures-util = "0.3.31"
env_logger = "0.11.8"
